server:
  port: ${PORT:9999}
spring:
  jackson:
    default-property-inclusion: non_null
  flyway:
    enabled: true
    locations: "classpath:db/migration"
  datasource:
    url: jdbc:mysql://localhost:5432/usercard-db
    username: usercard
    password: usercard
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect