server:
  port: ${PORT:9999}
spring:
  jackson:
    default-property-inclusion: non_null
  flyway:
    enabled: true
    locations: "classpath:db/migration"
  datasource:
    url: jdbc:postgresql://localhost:5432/usercard
    username: usercard
    password: usercard
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect